### ISSUE TITLE
Install firmware

### ISSUE THREAD

**Issue by rchsss** [nicoelayda/mdloader#1]
First, I would like to say thank you for creating a fork version of mdloader. 
This has helped me flash my DROP CTRL keyboard. Will I be able to load my own firmware configs and save after each PC reboot? or will it not work because smartEEPROM isn't enabled on my own firmware configs?

**Comment by nicoelayda** [comment]
@rchsss Firmware that you create from the [Drop Configurator](https://drop.com/mechanical-keyboards/configurator) or [QMK Configurator](https://config.qmk.fm/) will not work, since they do not have support for SmartEEPROM.

You will need to make your changes to the keymap source from [this branch](https://github.com/nicoelayda/qmk_firmware/tree/feature/smart-eeprom/keyboards/massdrop/ctrl) and compile the firmware.
